const STORE_KEY='pocketLedgerDataV1';
const expenseCategories=['Food','Shopping','Transport','Bills','Entertainment','Health','Education','Travel','Housing','Debt repayment','Other'];
const incomeCategories=['Main income','Side income','Bonus','Angpau / Gift','Bank interest','Investment income','Refund','Cashback','Allowance','Other income'];
const iconMap={
  'Food':'🍜','Shopping':'🛍️','Flight':'✈️','Transport':'🚗','Bills':'🧾','Entertainment':'🎬','Health':'💊','Education':'📚','Travel':'✈️','Housing':'🏠','Debt repayment':'💳','Other':'✨',
  'Main income':'💼','Side income':'💻','Bonus':'🎉','Angpau / Gift':'🧧','Bank interest':'🏦','Investment income':'📈','Refund':'↩️','Cashback':'💸','Allowance':'🪙','Other income':'💰','Transfer':'⇄'
};
let state=load();
let txType='expense';
let activeDebtId=null;
let reportMode='expense';
let pendingAccountLogo=null;
let pendingAccountEmoji='';

function defaults(){return {settings:{homeCurrency:'MYR',balancesHidden:false,balanceView:'all',balanceAccountId:''},accounts:[],transactions:[],trips:[],debts:[]}}
function migrate(raw){
  const base=defaults(); const s={...base,...raw};
  s.settings={...base.settings,...(raw.settings||{})};
  s.accounts=Array.isArray(raw.accounts)?raw.accounts:[]; s.transactions=Array.isArray(raw.transactions)?raw.transactions:[]; s.trips=Array.isArray(raw.trips)?raw.trips:[]; s.debts=Array.isArray(raw.debts)?raw.debts:[];
  s.trips.forEach(t=>{if(!Array.isArray(t.expenses))t.expenses=[];if(!Array.isArray(t.partners)||!t.partners.length)t.partners=['Me'];if(!t.partners.includes('Me'))t.partners.unshift('Me');if(!Array.isArray(t.settlements))t.settlements=[]});
  s.debts.forEach(d=>{if(!Array.isArray(d.payments))d.payments=[]});
  return s;
}
function load(){try{return migrate(JSON.parse(localStorage.getItem(STORE_KEY)||'{}'))}catch{return defaults()}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));renderAll()}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function money(v,c=state.settings.homeCurrency){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(Number(v)||0)}catch{return `${c} ${Number(v||0).toFixed(2)}`}}
function today(){return new Date().toISOString().slice(0,10)}
function currentMonth(){return today().slice(0,7)}
function monthKey(d){return (d||'').slice(0,7)}
function esc(s){return String(s??'').replace(/[&<>'"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[m]))}
function categoryIcon(cat,type){return iconMap[cat]||(type==='income'?'💰':type==='transfer'?'⇄':'🧾')}
function isLiabilityAccount(a){return ['Pay Later / BNPL','Credit card'].includes(a?.type)}
function accountTypeIcon(type){return type==='Bank'?'🏦':type==='E-wallet'?'📱':type==='Cash'?'💵':type==='Pay Later / BNPL'?'🛒':type==='Credit card'?'💳':'🧰'}
function accountBalance(a){let b=Number(a.opening||0), liability=isLiabilityAccount(a);for(const t of state.transactions){const amt=Number(t.amount||0);if(t.accountId===a.id){if(t.type==='expense')b+=liability?amt:-amt;if(t.type==='income')b+=liability?-amt:amt;if(t.type==='transfer')b+=liability?amt:-amt;if(t.type==='adjustment')b+=t.direction==='in'?amt:-amt}if(t.toAccountId===a.id&&t.type==='transfer')b+=liability?-amt:amt}return b}
function netWorthInHomeCurrency(){return state.accounts.filter(a=>a.currency===state.settings.homeCurrency).reduce((s,a)=>s+(isLiabilityAccount(a)?-accountBalance(a):accountBalance(a)),0)}
function transactionsForMonth(m){return state.transactions.filter(t=>monthKey(t.date)===m)}
function loanTypeLabel(type){return ({housing:'Housing · reducing balance',carReducing:'Car · reducing balance',carFlat:'Car · legacy flat-rate estimate',ptptn:'PTPTN / Ujrah estimate',personal:'Personal · reducing balance',custom:'Custom debt'})[type]||'Debt'}
function isReducing(type){return ['housing','carReducing','personal'].includes(type)}
function calcMonthlyPayment(d){
  const p=Number(d.principal||0), n=Math.max(1,Number(d.months||1)), annual=Number(d.rate||0)/100;
  if(Number(d.monthlyPayment)>0)return Number(d.monthlyPayment);
  if(d.type==='carFlat'||d.type==='ptptn'){const interest=p*annual*(n/12);return (p+interest)/n}
  if(isReducing(d.type)&&annual>0){const r=annual/12;return p*r*Math.pow(1+r,n)/(Math.pow(1+r,n)-1)}
  return p/n;
}
function debtPrincipalPaid(d){return (d.payments||[]).reduce((s,p)=>s+Number(p.principalPortion||p.amount||0),0)}
function debtOutstanding(d){return Math.max(0,Number(d.principal||0)-debtPrincipalPaid(d))}
function debtPaymentSplit(d,amount){
  const remaining=debtOutstanding(d), a=Math.max(0,Number(amount||0)); let interest=0;
  if(isReducing(d.type))interest=remaining*(Number(d.rate||0)/100)/12;
  else if(d.type==='carFlat'||d.type==='ptptn')interest=Number(d.principal||0)*(Number(d.rate||0)/100)/12;
  interest=Math.min(a,Math.max(0,interest)); const principal=Math.min(remaining,Math.max(0,a-interest)); return {interestPortion:interest,principalPortion:principal};
}

function renderAll(){renderAccounts();renderSelectors();renderBalanceScopeSelector();renderOverview();renderTrips();renderDebts();renderInsights();document.getElementById('homeCurrency').value=state.settings.homeCurrency}
function renderBalanceScopeSelector(){
  const sel=document.getElementById('balanceScopeSelect'); if(!sel)return;
  const current=state.settings.balanceView==='account'&&state.accounts.some(a=>a.id===state.settings.balanceAccountId)?state.settings.balanceAccountId:'all';
  sel.innerHTML=`<option value="all">All ${esc(state.settings.homeCurrency)} accounts</option>`+state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');
  sel.value=current;
}
function renderOverview(){
  const hidden=!!state.settings.balancesHidden; let shownValue=0,shownCurrency=state.settings.homeCurrency;
  if(state.settings.balanceView==='account'){
    const a=state.accounts.find(x=>x.id===state.settings.balanceAccountId);
    if(a){shownValue=isLiabilityAccount(a)?-accountBalance(a):accountBalance(a);shownCurrency=a.currency}else{state.settings.balanceView='all';state.settings.balanceAccountId='';shownValue=netWorthInHomeCurrency()}
  }else shownValue=netWorthInHomeCurrency();
  document.getElementById('netBalance').textContent=hidden?'••••••':money(shownValue,shownCurrency); document.getElementById('toggleBalanceBtn').textContent=hidden?'○':'◉'; document.getElementById('toggleBalanceBtn').setAttribute('aria-label',hidden?'Show balance':'Hide balance');
  const txs=transactionsForMonth(currentMonth()); const inc=txs.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0); const exp=txs.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0);
  document.getElementById('monthIncome').textContent=money(inc); document.getElementById('monthExpense').textContent=money(exp);
  const [y,m]=currentMonth().split('-'); document.getElementById('monthLabel').textContent=new Date(Number(y),Number(m)-1,1).toLocaleDateString(undefined,{month:'long',year:'numeric'});
  const sums={}; txs.filter(t=>t.type==='expense').forEach(t=>sums[t.category]=(sums[t.category]||0)+Number(t.amount)); const max=Math.max(1,...Object.values(sums));
  document.getElementById('categorySummary').innerHTML=Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="item"><div class="txLeft" style="flex:1"><div class="txIcon">${categoryIcon(k,'expense')}</div><div style="flex:1"><div class="title">${esc(k)}</div><div class="bar"><span style="width:${v/max*100}%"></span></div></div></div><div class="amount" style="margin-left:12px">${money(v)}</div></div>`).join('')||'<div class="item"><div class="sub">No expenses this month yet.</div></div>';
  const recent=[...state.transactions].sort((a,b)=>(b.date||'').localeCompare(a.date||'')).slice(0,8);
  document.getElementById('recentList').innerHTML=recent.map(t=>{const a=state.accounts.find(x=>x.id===t.accountId);const sign=t.type==='expense'||(t.type==='adjustment'&&t.direction==='out')?'-':t.type==='income'||(t.type==='adjustment'&&t.direction==='in')?'+':'';const cls=sign==='-'?'negative':sign==='+'?'positive':'';return `<div class="item"><div class="txLeft"><div class="txIcon">${categoryIcon(t.category,t.type)}</div><div><div class="title">${esc(t.note||t.category||t.type)}</div><div class="sub">${esc(t.date)} · ${esc(a?.name||'Account')}</div></div></div><div class="amount ${cls}">${sign}${money(t.amount,a?.currency||state.settings.homeCurrency)}</div></div>`}).join('')||'<div class="item"><div class="sub">No transactions yet.</div></div>';
}
function accountLogoMarkup(a){return a.logo?`<img class="accountLogoImg" src="${esc(a.logo)}" alt="">`:a.logoEmoji?`<span class="accountEmojiLogo">${esc(a.logoEmoji)}</span>`:accountTypeIcon(a.type)}
function renderAccounts(){document.getElementById('accountList').innerHTML=state.accounts.map(a=>{const liability=isLiabilityAccount(a);return `<button class="item" onclick="editAccount('${a.id}')"><div class="txLeft"><div class="txIcon accountLogoBox">${accountLogoMarkup(a)}</div><div><div class="title">${esc(a.name)}</div><div class="sub">${esc(a.type)} · ${esc(a.currency)} · tap to edit</div></div></div><div class="right"><div class="amount ${liability?'negative':''}">${money(accountBalance(a),a.currency)}</div>${liability?'<div class="sub">owed</div>':''}</div></button>`}).join('')||'<div class="item"><div class="sub">Add your first bank, e-wallet, cash, Pay Later or credit account.</div></div>'}
function renderSelectors(){const opts=state.accounts.map(a=>`<option value="${a.id}">${esc(a.name)} (${a.currency})</option>`).join('');document.getElementById('txAccount').innerHTML=opts;document.getElementById('txToAccount').innerHTML=opts;document.getElementById('debtPayAccount').innerHTML=opts;const optional='<option value="">Do not link to an account</option>'+opts;document.getElementById('tripExpenseAccount').innerHTML=optional;document.getElementById('settlementAccount').innerHTML=optional;renderCategoryOptions()}
function renderCategoryOptions(){const cats=txType==='income'?incomeCategories:expenseCategories;document.getElementById('txCategory').innerHTML=cats.map(c=>`<option>${esc(c)}</option>`).join('')}
function renderTrips(){const list=document.getElementById('tripList');list.innerHTML=state.trips.map(t=>`<button class="item" onclick="openTrip('${t.id}')"><div class="txLeft"><div class="txIcon">✈️</div><div><div class="title">${esc(t.name)}</div><div class="sub">${t.partners.length} member${t.partners.length===1?'':'s'} · ${esc(t.currency)}</div></div></div><div>›</div></button>`).join('')||'<div class="item"><div class="sub">Create a trip to track shared travel spending.</div></div>'}
function renderInsights(){
  const input=document.getElementById('reportMonth'); if(!input.value)input.value=currentMonth(); const m=input.value||currentMonth(); const txs=transactionsForMonth(m);
  const inc=txs.filter(t=>t.type==='income').reduce((s,t)=>s+Number(t.amount),0), exp=txs.filter(t=>t.type==='expense').reduce((s,t)=>s+Number(t.amount),0), net=inc-exp;
  const selected=reportMode==='expense'?exp:inc, other=reportMode==='expense'?inc:exp;
  document.getElementById('reportTitle').textContent=reportMode==='expense'?'Expense overview':'Income overview';
  document.getElementById('selectedTotalLabel').textContent=reportMode==='expense'?'Expenses':'Income';
  document.getElementById('selectedTotal').textContent=money(selected);document.getElementById('selectedTotal').className=reportMode==='expense'?'negative':'positive';
  document.getElementById('otherTotal').textContent=money(other);document.getElementById('otherTotal').className=reportMode==='expense'?'positive':'negative';
  document.getElementById('reportNet').textContent=(net>=0?'+ ':'- ')+money(Math.abs(net));document.getElementById('reportNet').className=net>=0?'positive':'negative';
  document.querySelectorAll('#reportModeSeg button').forEach(b=>b.classList.toggle('active',b.dataset.mode===reportMode));
  const modeTxs=txs.filter(t=>t.type===reportMode); const sums={}; modeTxs.forEach(t=>sums[t.category]=(sums[t.category]||0)+Number(t.amount));
  document.getElementById('pieHeading').textContent=reportMode==='expense'?'Expenses by category':'Income by category';
  document.getElementById('trendHeading').textContent=reportMode==='expense'?'6-month expense trend':'6-month income trend';
  renderPie(sums,selected,reportMode); renderTrend(reportMode,m); renderBreakdown('reportBreakdown',modeTxs,reportMode);
}
function renderPie(sums,total,type){const entries=Object.entries(sums).sort((a,b)=>b[1]-a[1]);const colors=['#111827','#4f46e5','#0891b2','#16a34a','#f59e0b','#e11d48','#7c3aed','#0f766e','#ea580c','#64748b'];let start=0,stops=[];entries.forEach(([k,v],i)=>{const pct=total?100*v/total:0;stops.push(`${colors[i%colors.length]} ${start}% ${start+pct}%`);start+=pct});const pie=document.getElementById('pieChart');pie.style.background=entries.length?`conic-gradient(${stops.join(',')})`:'#e9edf2';document.getElementById('pieTotal').textContent=money(total);document.getElementById('pieLegend').innerHTML=entries.map(([k,v],i)=>{const pct=total?100*v/total:0;return `<div class="legendRow"><span class="legendDot" style="background:${colors[i%colors.length]}"></span><span class="legendName">${categoryIcon(k,type)} ${esc(k)}</span><strong>${pct.toFixed(1)}%</strong><span class="legendAmount">${money(v)}</span></div>`}).join('')||'<div class="sub">No data for this month.</div>'}
function shiftMonth(m,delta){const [y,mo]=m.split('-').map(Number);const d=new Date(y,mo-1+delta,1);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}`}
function monthShort(m){const [y,mo]=m.split('-').map(Number);return new Date(y,mo-1,1).toLocaleDateString(undefined,{month:'short'})}
function renderTrend(type,endMonth){const months=Array.from({length:6},(_,i)=>shiftMonth(endMonth,i-5));const vals=months.map(m=>transactionsForMonth(m).filter(t=>t.type===type).reduce((s,t)=>s+Number(t.amount),0));const max=Math.max(1,...vals),w=330,h=150,padX=20,padY=20,plotW=w-padX*2,plotH=h-padY*2;const pts=vals.map((v,i)=>[padX+(plotW*i/(months.length-1)),padY+plotH-(v/max*plotH)]);const poly=pts.map(p=>p.join(',')).join(' ');const dots=pts.map((p,i)=>`<circle cx="${p[0]}" cy="${p[1]}" r="4"></circle><text x="${p[0]}" y="${h-3}" text-anchor="middle">${monthShort(months[i])}</text>`).join('');document.getElementById('trendChart').innerHTML=`<svg viewBox="0 0 ${w} ${h}" role="img" aria-label="Six month ${type} trend"><line x1="${padX}" y1="${padY+plotH}" x2="${w-padX}" y2="${padY+plotH}" class="axisLine"></line><polyline points="${poly}" class="trendLine"></polyline>${dots}</svg><div class="trendValues">${months.map((m,i)=>`<span>${money(vals[i])}</span>`).join('')}</div>`}
function renderBreakdown(el,txs,type){const sums={};txs.forEach(t=>sums[t.category]=(sums[t.category]||0)+Number(t.amount));const max=Math.max(1,...Object.values(sums));document.getElementById(el).innerHTML=Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="item"><div class="txLeft" style="flex:1"><div class="txIcon">${categoryIcon(k,type)}</div><div style="flex:1"><div class="title">${esc(k)}</div><div class="bar"><span style="width:${v/max*100}%"></span></div></div></div><div class="amount ${type==='income'?'positive':''}">${money(v)}</div></div>`).join('')||`<div class="item"><div class="sub">No ${type} transactions for this month.</div></div>`}
function renderDebts(){
  const home=state.settings.homeCurrency; const homeDebts=state.debts.filter(d=>d.currency===home); const total=homeDebts.reduce((s,d)=>s+debtOutstanding(d),0); const foreign=state.debts.filter(d=>d.currency!==home).length;
  document.getElementById('totalDebt').textContent=money(total,home)+(foreign?` + ${foreign} foreign-currency debt${foreign>1?'s':''}`:'');
  document.getElementById('debtList').innerHTML=state.debts.map(d=>{const out=debtOutstanding(d), pct=Math.max(0,Math.min(100,(1-out/Math.max(1,Number(d.principal)))*100)), mp=calcMonthlyPayment(d);return `<button class="item" onclick="openDebt('${d.id}')"><div style="flex:1"><div class="title">${esc(d.name)}</div><div class="debtTypePill">${esc(loanTypeLabel(d.type))}</div><div class="sub" style="margin-top:7px">Est. payment ${money(mp,d.currency)} / month</div><div class="debtProgress"><span style="width:${pct}%"></span></div></div><div class="amount" style="margin-left:12px">${money(out,d.currency)}</div></button>`}).join('')||'<div class="item"><div class="sub">No debts recorded yet.</div></div>';
}

function tripSettlementSuggestions(t){
  const paid={},share={};t.partners.forEach(p=>{paid[p]=0;share[p]=0});
  t.expenses.forEach(e=>{paid[e.paidBy]=(paid[e.paidBy]||0)+Number(e.amount);const each=Number(e.amount)/Math.max(1,e.sharedBy.length);e.sharedBy.forEach(p=>share[p]=(share[p]||0)+each)});
  const net={};t.partners.forEach(p=>net[p]=(paid[p]||0)-(share[p]||0));
  (t.settlements||[]).forEach(x=>{net[x.from]=(net[x.from]||0)+Number(x.amount);net[x.to]=(net[x.to]||0)-Number(x.amount)});
  const debtors=Object.entries(net).filter(([,v])=>v<-.01).map(([p,v])=>[p,-v]);const creditors=Object.entries(net).filter(([,v])=>v>.01).map(([p,v])=>[p,v]);const out=[];let i=0,j=0;
  while(i<debtors.length&&j<creditors.length){const amt=Math.min(debtors[i][1],creditors[j][1]);out.push({from:debtors[i][0],to:creditors[j][0],amount:amt});debtors[i][1]-=amt;creditors[j][1]-=amt;if(debtors[i][1]<.01)i++;if(creditors[j][1]<.01)j++}
  return out;
}
window.openTrip=function(tripId){
  const t=state.trips.find(x=>x.id===tripId);if(!t)return;const total=t.expenses.reduce((s,e)=>s+Number(e.amount),0);const byCat={};t.expenses.forEach(e=>byCat[e.category]=(byCat[e.category]||0)+Number(e.amount));const settles=tripSettlementSuggestions(t);const d=document.getElementById('tripDetail');d.classList.remove('hidden');
  d.innerHTML=`<div class="sectionHead"><div><h2>${esc(t.name)}</h2><div class="sub">${t.partners.map(esc).join(' · ')}</div></div><div class="row"><button class="secondary small" onclick="editTrip('${t.id}')">Edit</button><button class="primary small" onclick="addTripExpense('${t.id}')">+ Expense</button></div></div><div class="card"><div class="muted">Trip total</div><div class="balance darkBalance">${money(total,t.currency)}</div><div class="tripTotals">${Object.entries(byCat).map(([k,v])=>`<div class="miniCard"><div class="muted">${esc(k)}</div><strong>${money(v,t.currency)}</strong></div>`).join('')||'<div class="sub">No spending yet.</div>'}</div></div><div class="sectionHead"><h2>Settlement</h2><button class="secondary small" onclick="openSettlement('${t.id}')">+ Settlement</button></div><div class="stack">${settles.map((x,i)=>`<div class="item"><div><div class="title">${esc(x.from)} pays ${esc(x.to)}</div><div class="sub">Remaining suggested settlement</div></div><div class="right"><div class="amount">${money(x.amount,t.currency)}</div><button class="secondary tinyAction" onclick="openSuggestedSettlement('${t.id}',${i})">Settle</button></div></div>`).join('')||'<div class="item"><div class="sub">Everyone is settled.</div></div>'}</div>${(t.settlements||[]).length?`<div class="sectionHead"><h2>Recorded settlements</h2></div><div class="stack">${[...t.settlements].reverse().map(x=>`<div class="item"><div><div class="title">${esc(x.from)} → ${esc(x.to)}</div><div class="sub">${esc(x.date||'')} ${x.accountId?'· linked to account':''}</div></div><div class="amount">${money(x.amount,t.currency)}</div></div>`).join('')}</div>`:''}<div class="sectionHead"><h2>Expenses</h2></div><div class="stack">${t.expenses.map(e=>`<div class="item"><div class="txLeft"><div class="txIcon">${categoryIcon(e.category,'expense')}</div><div><div class="title">${esc(e.description)}</div><div class="sub">${esc(e.category)} · paid by ${esc(e.paidBy)}${e.accountId?' · linked':''}</div></div></div><div class="amount">${money(e.amount,t.currency)}</div></div>`).join('')||'<div class="item"><div class="sub">No trip expenses yet.</div></div>'}</div>`;d.scrollIntoView({behavior:'smooth'})
}
window.addTripExpense=function(tripId){const t=state.trips.find(x=>x.id===tripId);document.getElementById('tripExpenseForm').reset();document.getElementById('tripExpenseTripId').value=tripId;document.getElementById('tripExpensePaidBy').innerHTML=t.partners.map(p=>`<option>${esc(p)}</option>`).join('');document.getElementById('tripExpenseSharedBy').innerHTML=t.partners.map(p=>`<label><input type="checkbox" value="${esc(p)}" checked>${esc(p)}</label>`).join('');renderSelectors();document.getElementById('tripExpenseDialog').showModal()}
window.editTrip=function(tripId){const t=state.trips.find(x=>x.id===tripId);if(!t)return;document.getElementById('editTripId').value=t.id;document.getElementById('editTripName').value=t.name;document.getElementById('editTripCurrency').value=t.currency;document.getElementById('editTripPartners').value=t.partners.filter(p=>p!=='Me').join(', ');document.getElementById('editTripDialog').showModal()}
window.openSuggestedSettlement=function(tripId,index){const t=state.trips.find(x=>x.id===tripId);if(!t)return;const x=tripSettlementSuggestions(t)[index];if(x)openSettlement(tripId,x.from,x.to,x.amount)}
window.openSettlement=function(tripId,from='',to='',amount=''){const t=state.trips.find(x=>x.id===tripId);if(!t)return;const opts=t.partners.map(p=>`<option>${esc(p)}</option>`).join('');document.getElementById('settlementTripId').value=t.id;document.getElementById('settlementFrom').innerHTML=opts;document.getElementById('settlementTo').innerHTML=opts;document.getElementById('settlementFrom').value=from||t.partners[0];document.getElementById('settlementTo').value=to||t.partners.find(p=>p!==document.getElementById('settlementFrom').value)||t.partners[0];document.getElementById('settlementAmount').value=amount?Number(amount).toFixed(2):'';document.getElementById('settlementDate').value=today();renderSelectors();document.getElementById('settlementDialog').showModal()}
window.editAccount=function(accountId){const a=state.accounts.find(x=>x.id===accountId);if(!a)return;pendingAccountLogo=a.logo||null;pendingAccountEmoji=a.logoEmoji||'';document.getElementById('accountEmoji').value=pendingAccountEmoji;updateLogoPreview();document.getElementById('accountDialogTitle').textContent='Edit account';document.getElementById('accountEditId').value=a.id;document.getElementById('accountName').value=a.name;document.getElementById('accountType').value=a.type;document.getElementById('accountCurrency').value=a.currency;document.getElementById('openingBalanceWrap').classList.add('hidden');document.getElementById('currentBalanceWrap').classList.remove('hidden');document.getElementById('accountCurrent').value=accountBalance(a).toFixed(2);document.getElementById('accountBalanceHint').classList.remove('hidden');document.getElementById('accountBalanceHint').textContent=isLiabilityAccount(a)?'For Pay Later / credit accounts, this is the amount currently owed. Changing it keeps your transaction history unchanged.':'Changing this adjusts the account opening balance by the difference, so your transaction history stays unchanged.';document.getElementById('accountDialog').showModal()}
window.openDebt=function(debtId){const d=state.debts.find(x=>x.id===debtId);if(!d)return;activeDebtId=d.id;const out=debtOutstanding(d), paid=debtPrincipalPaid(d), payment=calcMonthlyPayment(d), totalPaid=(d.payments||[]).reduce((s,p)=>s+Number(p.amount),0);document.getElementById('debtDetailTitle').textContent=d.name;document.getElementById('debtDetailBody').innerHTML=`<div class="card" style="box-shadow:none;background:#f7f8fa"><div class="muted">Outstanding principal estimate</div><div class="balance darkBalance">${money(out,d.currency)}</div><div class="debtMeta"><div class="miniCard"><div class="muted">Starting amount</div><strong>${money(d.principal,d.currency)}</strong></div><div class="miniCard"><div class="muted">Est. monthly</div><strong>${money(payment,d.currency)}</strong></div><div class="miniCard"><div class="muted">Rate</div><strong>${Number(d.rate||0).toFixed(2)}%</strong></div><div class="miniCard"><div class="muted">Total paid</div><strong>${money(totalPaid,d.currency)}</strong></div></div><div class="softNote">${esc(debtExplanation(d))}</div></div>${(d.payments||[]).length?`<div class="sectionHead"><h2>Recent payments</h2></div><div class="stack">${[...d.payments].reverse().slice(0,5).map(p=>`<div class="item"><div><div class="title">${esc(p.date)}</div><div class="sub">Principal ${money(p.principalPortion,d.currency)} · interest/fee ${money(p.interestPortion,d.currency)}</div></div><div class="amount">${money(p.amount,d.currency)}</div></div>`).join('')}</div>`:''}`;document.getElementById('debtDetailDialog').showModal()}
function debtExplanation(d){if(d.type==='carFlat')return 'Legacy flat-rate display is only an estimate. Early-settlement/rebate figures may differ from the scheduled balance.';if(d.type==='ptptn')return 'PTPTN/Ujrah mode uses the rate you entered as a simple estimate. Check your official PTPTN statement for the exact amount due.';if(isReducing(d.type))return 'Monthly estimate uses a standard reducing-balance amortisation formula. Floating rates and lender-specific fees can change the real payment.';return 'Custom debt uses the amount, rate and payment details you entered.'}

function updateLogoPreview(){const el=document.getElementById('accountLogoPreview');el.innerHTML=pendingAccountLogo?`<img class="accountLogoImg" src="${esc(pendingAccountLogo)}" alt="">`:pendingAccountEmoji?`<span class="accountEmojiLogo">${esc(pendingAccountEmoji)}</span>`:accountTypeIcon(document.getElementById('accountType')?.value||'Bank')}
function resizeLogoFile(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>{const img=new Image();img.onload=()=>{const size=128,canvas=document.createElement('canvas');canvas.width=size;canvas.height=size;const ctx=canvas.getContext('2d');ctx.clearRect(0,0,size,size);const scale=Math.min(size/img.width,size/img.height),w=img.width*scale,h=img.height*scale;ctx.drawImage(img,(size-w)/2,(size-h)/2,w,h);resolve(canvas.toDataURL('image/png',.9))};img.onerror=reject;img.src=reader.result};reader.onerror=reject;reader.readAsDataURL(file)})}

function setScreen(screenId){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===screenId));document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.screen===screenId));const names={overview:'Overview',accounts:'Accounts',add:'Add transaction',travel:'Travel',settings:'Settings',insights:reportMode==='expense'?'Expense overview':'Income overview',debt:'Debt'};document.getElementById('screenTitle').textContent=names[screenId]||'Pocket Ledger';window.scrollTo({top:0,behavior:'smooth'})}
document.querySelectorAll('.tabbar button').forEach(b=>b.addEventListener('click',()=>setScreen(b.dataset.screen)));
document.querySelectorAll('[data-back]').forEach(b=>b.addEventListener('click',()=>setScreen('overview')));
document.getElementById('openIncomeOverviewBtn').onclick=()=>{reportMode='income';renderInsights();setScreen('insights')};document.getElementById('openExpenseOverviewBtn').onclick=()=>{reportMode='expense';renderInsights();setScreen('insights')};document.getElementById('openDebtBtn').onclick=()=>{renderDebts();setScreen('debt')};document.querySelectorAll('#reportModeSeg button').forEach(b=>b.addEventListener('click',()=>{reportMode=b.dataset.mode;renderInsights();document.getElementById('screenTitle').textContent=reportMode==='expense'?'Expense overview':'Income overview'}));
document.getElementById('toggleBalanceBtn').onclick=()=>{state.settings.balancesHidden=!state.settings.balancesHidden;save()};document.getElementById('balanceScopeSelect').addEventListener('change',e=>{if(e.target.value==='all'){state.settings.balanceView='all';state.settings.balanceAccountId=''}else{state.settings.balanceView='account';state.settings.balanceAccountId=e.target.value}save()});
document.querySelectorAll('#txTypeSeg button').forEach(b=>b.addEventListener('click',()=>{txType=b.dataset.type;document.querySelectorAll('#txTypeSeg button').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('toAccountWrap').classList.toggle('hidden',txType!=='transfer');document.getElementById('categoryWrap').classList.toggle('hidden',txType==='transfer');renderCategoryOptions()}));

document.getElementById('addAccountBtn').onclick=()=>{document.getElementById('accountForm').reset();pendingAccountLogo=null;pendingAccountEmoji='';document.getElementById('accountEmoji').value='';document.getElementById('accountDialogTitle').textContent='Add account';document.getElementById('accountEditId').value='';document.getElementById('openingBalanceWrap').classList.remove('hidden');document.getElementById('currentBalanceWrap').classList.add('hidden');document.getElementById('accountBalanceHint').classList.add('hidden');document.getElementById('accountOpening').value='0';updateLogoPreview();document.getElementById('accountDialog').showModal()};
document.getElementById('accountType').addEventListener('change',updateLogoPreview);
document.getElementById('accountEmoji').addEventListener('input',e=>{pendingAccountEmoji=e.target.value.trim();updateLogoPreview()});
document.getElementById('accountLogo').addEventListener('change',async e=>{const f=e.target.files?.[0];if(!f)return;try{pendingAccountLogo=await resizeLogoFile(f);updateLogoPreview()}catch{alert('Could not read this image.')}});
document.getElementById('removeAccountLogoBtn').onclick=()=>{pendingAccountLogo=null;pendingAccountEmoji='';document.getElementById('accountLogo').value='';document.getElementById('accountEmoji').value='';updateLogoPreview()};
document.getElementById('accountForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const editId=document.getElementById('accountEditId').value;const name=document.getElementById('accountName').value.trim();if(!name)return;if(editId){const a=state.accounts.find(x=>x.id===editId);const desired=Number(document.getElementById('accountCurrent').value||0);a.name=name;a.type=document.getElementById('accountType').value;a.currency=document.getElementById('accountCurrency').value;a.logo=pendingAccountLogo||null;a.logoEmoji=pendingAccountEmoji||'';a.opening=0;const transactionEffect=accountBalance(a);a.opening=desired-transactionEffect}else{state.accounts.push({id:id(),name,type:document.getElementById('accountType').value,currency:document.getElementById('accountCurrency').value,opening:Number(document.getElementById('accountOpening').value||0),logo:pendingAccountLogo||null,logoEmoji:pendingAccountEmoji||''})}save()});

document.getElementById('txDate').value=today();document.getElementById('txForm').addEventListener('submit',e=>{e.preventDefault();if(!state.accounts.length){alert('Add an account first.');return}const amount=Number(document.getElementById('txAmount').value);const accountId=document.getElementById('txAccount').value;const toAccountId=document.getElementById('txToAccount').value;if(txType==='transfer'&&accountId===toAccountId){alert('Choose two different accounts.');return}state.transactions.push({id:id(),type:txType,amount,accountId,toAccountId:txType==='transfer'?toAccountId:null,category:txType==='transfer'?'Transfer':document.getElementById('txCategory').value,date:document.getElementById('txDate').value,note:document.getElementById('txNote').value.trim()});save();e.target.reset();document.getElementById('txDate').value=today();renderCategoryOptions();setScreen('overview')});

document.getElementById('addTripBtn').onclick=()=>{document.getElementById('tripForm').reset();document.getElementById('tripDialog').showModal()};document.getElementById('tripForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const name=document.getElementById('tripName').value.trim();if(!name)return;state.trips.push({id:id(),name,currency:document.getElementById('tripCurrency').value,partners:['Me'],expenses:[],settlements:[]});save();e.target.reset()});
document.getElementById('editTripForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const t=state.trips.find(x=>x.id===document.getElementById('editTripId').value);if(!t)return;const newCurrency=document.getElementById('editTripCurrency').value;if(newCurrency!==t.currency&&(t.expenses.length||(t.settlements||[]).length)&&!confirm('Changing currency will relabel existing trip amounts without converting them. Continue?')){e.preventDefault();return}const entered=document.getElementById('editTripPartners').value.split(',').map(x=>x.trim()).filter(Boolean).filter(x=>x!=='Me');const used=new Set(['Me']);t.expenses.forEach(x=>{used.add(x.paidBy);(x.sharedBy||[]).forEach(p=>used.add(p))});(t.settlements||[]).forEach(x=>{used.add(x.from);used.add(x.to)});t.name=document.getElementById('editTripName').value.trim();t.currency=newCurrency;t.partners=[...new Set(['Me',...entered,...[...used].filter(x=>x!=='Me')])];save();setTimeout(()=>openTrip(t.id),0)});
document.getElementById('deleteTripBtn').onclick=()=>{const id=document.getElementById('editTripId').value,t=state.trips.find(x=>x.id===id);if(!t)return;if(confirm(`Delete ${t.name} and all linked account transactions created from this trip?`)){state.trips=state.trips.filter(x=>x.id!==id);state.transactions=state.transactions.filter(x=>x.tripId!==id);document.getElementById('editTripDialog').close();document.getElementById('tripDetail').classList.add('hidden');save()}};
document.getElementById('tripExpenseForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const t=state.trips.find(x=>x.id===document.getElementById('tripExpenseTripId').value);const shared=[...document.querySelectorAll('#tripExpenseSharedBy input:checked')].map(x=>x.value);if(!shared.length){e.preventDefault();alert('Choose at least one person to share the expense.');return}const paidBy=document.getElementById('tripExpensePaidBy').value,accountId=document.getElementById('tripExpenseAccount').value;if(accountId&&paidBy!=='Me'){e.preventDefault();alert('Only expenses paid by Me can be linked to one of your accounts. Choose “Do not link” or change Paid by to Me.');return}const expenseId=id(),amount=Number(document.getElementById('tripExpenseAmount').value),desc=document.getElementById('tripExpenseDesc').value.trim(),category=document.getElementById('tripExpenseCategory').value;t.expenses.push({id:expenseId,description:desc,amount,category,paidBy,sharedBy:shared,accountId:accountId||null});if(accountId)state.transactions.push({id:id(),type:'expense',amount,accountId,toAccountId:null,category:'Travel',date:today(),note:`${t.name}: ${desc}`,tripId:t.id,tripExpenseId:expenseId});save();setTimeout(()=>openTrip(t.id),0);e.target.reset()});
document.getElementById('settlementForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const t=state.trips.find(x=>x.id===document.getElementById('settlementTripId').value);if(!t)return;const from=document.getElementById('settlementFrom').value,to=document.getElementById('settlementTo').value,amount=Number(document.getElementById('settlementAmount').value),date=document.getElementById('settlementDate').value,accountId=document.getElementById('settlementAccount').value;if(from===to){e.preventDefault();alert('From and To must be different people.');return}if(accountId&&!['Me'].includes(from)&&!['Me'].includes(to)){e.preventDefault();alert('An account can only be linked when Me is paying or receiving.');return}const settlementId=id();t.settlements.push({id:settlementId,from,to,amount,date,accountId:accountId||null});if(accountId&&from==='Me')state.transactions.push({id:id(),type:'expense',amount,accountId,toAccountId:null,category:'Travel',date,note:`${t.name}: settlement to ${to}`,tripId:t.id,tripSettlementId:settlementId});if(accountId&&to==='Me')state.transactions.push({id:id(),type:'adjustment',direction:'in',amount,accountId,toAccountId:null,category:'Travel settlement',date,note:`${t.name}: repayment from ${from}`,tripId:t.id,tripSettlementId:settlementId});save();setTimeout(()=>openTrip(t.id),0)});

document.getElementById('reportMonth').value=currentMonth();document.getElementById('reportMonth').addEventListener('change',renderInsights);
document.getElementById('addDebtBtn').onclick=()=>{document.getElementById('debtForm').reset();document.getElementById('debtDialogTitle').textContent='Add debt';document.getElementById('debtEditId').value='';document.getElementById('debtPrincipalWrap').classList.remove('hidden');document.getElementById('debtOutstandingWrap').classList.add('hidden');document.getElementById('debtRate').value='4';document.getElementById('debtMonths').value='60';document.getElementById('debtDialog').showModal();updateDebtHint()};
document.getElementById('debtType').addEventListener('change',updateDebtHint);function updateDebtHint(){const type=document.getElementById('debtType').value;const el=document.getElementById('debtModeHint');if(type==='ptptn'){el.textContent='PTPTN/Ujrah estimate. The rate remains editable; check your official statement for the exact repayment schedule.';if(document.getElementById('debtRate').value==='4')document.getElementById('debtRate').value='1'}else if(type==='carFlat'){el.textContent='Legacy flat-rate estimate. Useful for older agreements, but not an early-settlement quote.'}else if(isReducing(type)){el.textContent='Reducing-balance amortisation estimate. Floating/reference-rate changes are not predicted.'}else el.textContent='Custom debt: use the rate and monthly payment from your statement.'}
document.getElementById('debtForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const editId=document.getElementById('debtEditId').value;if(editId){const d=state.debts.find(x=>x.id===editId);const desired=Number(document.getElementById('debtOutstandingEdit').value||0);d.name=document.getElementById('debtName').value.trim();d.type=document.getElementById('debtType').value;d.currency=document.getElementById('debtCurrency').value;d.rate=Number(document.getElementById('debtRate').value||0);d.months=Number(document.getElementById('debtMonths').value||1);d.monthlyPayment=Number(document.getElementById('debtPayment').value||0);d.principal=desired+debtPrincipalPaid(d)}else{state.debts.push({id:id(),name:document.getElementById('debtName').value.trim(),type:document.getElementById('debtType').value,currency:document.getElementById('debtCurrency').value,principal:Number(document.getElementById('debtPrincipal').value),rate:Number(document.getElementById('debtRate').value||0),months:Number(document.getElementById('debtMonths').value||1),monthlyPayment:Number(document.getElementById('debtPayment').value||0),payments:[]})}save();e.target.reset()});
document.getElementById('closeDebtDetail').onclick=()=>document.getElementById('debtDetailDialog').close();document.getElementById('editDebtBtn').onclick=()=>{const d=state.debts.find(x=>x.id===activeDebtId);if(!d)return;document.getElementById('debtDetailDialog').close();document.getElementById('debtForm').reset();document.getElementById('debtDialogTitle').textContent='Edit debt';document.getElementById('debtEditId').value=d.id;document.getElementById('debtName').value=d.name;document.getElementById('debtType').value=d.type;document.getElementById('debtCurrency').value=d.currency;document.getElementById('debtRate').value=d.rate||0;document.getElementById('debtMonths').value=d.months||1;document.getElementById('debtPayment').value=d.monthlyPayment||'';document.getElementById('debtOutstandingEdit').value=debtOutstanding(d).toFixed(2);document.getElementById('debtPrincipalWrap').classList.add('hidden');document.getElementById('debtOutstandingWrap').classList.remove('hidden');updateDebtHint();document.getElementById('debtDialog').showModal()};
document.getElementById('recordDebtPaymentBtn').onclick=()=>{const d=state.debts.find(x=>x.id===activeDebtId);if(!d)return;if(!state.accounts.length){alert('Add an account first so the repayment can be recorded as an expense.');return}document.getElementById('debtPaymentDebtId').value=d.id;document.getElementById('debtPayAmount').value=calcMonthlyPayment(d).toFixed(2);document.getElementById('debtPayDate').value=today();document.getElementById('debtDetailDialog').close();document.getElementById('debtPaymentDialog').showModal()};
document.getElementById('debtPaymentForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const d=state.debts.find(x=>x.id===document.getElementById('debtPaymentDebtId').value);const amount=Number(document.getElementById('debtPayAmount').value),accountId=document.getElementById('debtPayAccount').value,date=document.getElementById('debtPayDate').value;const split=debtPaymentSplit(d,amount);d.payments.push({id:id(),amount,date,accountId,...split});state.transactions.push({id:id(),type:'expense',amount,accountId,toAccountId:null,category:'Debt repayment',date,note:`${d.name} payment`});save()});
document.getElementById('deleteDebtBtn').onclick=()=>{const d=state.debts.find(x=>x.id===activeDebtId);if(d&&confirm(`Delete ${d.name}? Existing expense transactions created by its past payments will be kept.`)){state.debts=state.debts.filter(x=>x.id!==activeDebtId);save();document.getElementById('debtDetailDialog').close()}};

document.getElementById('homeCurrency').addEventListener('change',e=>{state.settings.homeCurrency=e.target.value;save()});
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PocketLedger-backup-${today()}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
document.querySelectorAll('.dialogCancel').forEach(btn=>btn.addEventListener('click',()=>btn.closest('dialog')?.close()));
document.getElementById('exportBtn').onclick=exportData;document.getElementById('backupBtn').onclick=exportData;document.getElementById('importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{state=migrate(JSON.parse(await f.text()));save();alert('Backup restored.')}catch{alert('Invalid backup file.')}});document.getElementById('resetBtn').onclick=()=>{if(confirm('Erase all Pocket Ledger data stored on this device?')){state=defaults();save()}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();
