const STORE_KEY='pocketLedgerDataV1';
const categories=['Food','Shopping','Transport','Bills','Entertainment','Health','Education','Travel','Other'];
let state=load();
let txType='expense';

function defaults(){return {settings:{homeCurrency:'MYR'},accounts:[],transactions:[],trips:[]}}
function load(){try{return {...defaults(),...JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}}catch{return defaults()}}
function save(){localStorage.setItem(STORE_KEY,JSON.stringify(state));renderAll()}
function id(){return crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+Math.random().toString(36).slice(2)}
function money(v,c=state.settings.homeCurrency){try{return new Intl.NumberFormat(undefined,{style:'currency',currency:c}).format(v)}catch{return `${c} ${Number(v).toFixed(2)}`}}
function today(){return new Date().toISOString().slice(0,10)}
function monthKey(d){return d.slice(0,7)}
function currentMonth(){return today().slice(0,7)}

function accountBalance(a){let b=Number(a.opening||0);for(const t of state.transactions){if(t.accountId===a.id){if(t.type==='expense')b-=t.amount;if(t.type==='income')b+=t.amount;if(t.type==='transfer')b-=t.amount}if(t.toAccountId===a.id&&t.type==='transfer')b+=t.amount}return b}
function monthTransactions(){return state.transactions.filter(t=>monthKey(t.date)===currentMonth())}

function renderAll(){renderAccounts();renderSelectors();renderOverview();renderTrips();document.getElementById('homeCurrency').value=state.settings.homeCurrency}
function renderOverview(){
  const accounts=state.accounts; const balances=accounts.reduce((s,a)=>s+accountBalance(a),0); document.getElementById('netBalance').textContent=money(balances);
  const txs=monthTransactions(); const inc=txs.filter(t=>t.type==='income').reduce((s,t)=>s+t.amount,0); const exp=txs.filter(t=>t.type==='expense').reduce((s,t)=>s+t.amount,0);
  document.getElementById('monthIncome').textContent=money(inc); document.getElementById('monthExpense').textContent=money(exp);
  document.getElementById('monthLabel').textContent=new Date().toLocaleDateString(undefined,{month:'long',year:'numeric'});
  const sums={}; txs.filter(t=>t.type==='expense').forEach(t=>sums[t.category]=(sums[t.category]||0)+t.amount); const max=Math.max(1,...Object.values(sums));
  document.getElementById('categorySummary').innerHTML=Object.entries(sums).sort((a,b)=>b[1]-a[1]).map(([k,v])=>`<div class="item"><div style="flex:1"><div class="title">${k}</div><div class="bar"><span style="width:${v/max*100}%"></span></div></div><div class="amount" style="margin-left:12px">${money(v)}</div></div>`).join('')||'<div class="item"><div class="sub">No expenses this month yet.</div></div>';
  const recent=[...state.transactions].sort((a,b)=>b.date.localeCompare(a.date)).slice(0,8); document.getElementById('recentList').innerHTML=recent.map(t=>{const a=state.accounts.find(x=>x.id===t.accountId);return `<div class="item"><div><div class="title">${t.note||t.category||t.type}</div><div class="sub">${t.date} · ${a?.name||'Account'}</div></div><div class="amount ${t.type==='expense'?'negative':t.type==='income'?'positive':''}">${t.type==='expense'?'-':t.type==='income'?'+':''}${money(t.amount,a?.currency||state.settings.homeCurrency)}</div></div>`}).join('')||'<div class="item"><div class="sub">No transactions yet.</div></div>';
}
function renderAccounts(){document.getElementById('accountList').innerHTML=state.accounts.map(a=>`<div class="item"><div><div class="title">${a.name}</div><div class="sub">${a.type} · ${a.currency}</div></div><div class="amount">${money(accountBalance(a),a.currency)}</div></div>`).join('')||'<div class="item"><div class="sub">Add your first bank, e-wallet or cash account.</div></div>'}
function renderSelectors(){const opts=state.accounts.map(a=>`<option value="${a.id}">${a.name} (${a.currency})</option>`).join('');document.getElementById('txAccount').innerHTML=opts;document.getElementById('txToAccount').innerHTML=opts;document.getElementById('txCategory').innerHTML=categories.map(c=>`<option>${c}</option>`).join('')}
function renderTrips(){const list=document.getElementById('tripList');list.innerHTML=state.trips.map(t=>`<button class="item" style="border:0;text-align:left" onclick="openTrip('${t.id}')"><div><div class="title">${t.name}</div><div class="sub">${t.partners.length} partners · ${t.currency}</div></div><div>›</div></button>`).join('')||'<div class="item"><div class="sub">Create a trip to track shared travel spending.</div></div>'}
window.openTrip=function(tripId){const t=state.trips.find(x=>x.id===tripId);if(!t)return;const total=t.expenses.reduce((s,e)=>s+e.amount,0);const byCat={};t.expenses.forEach(e=>byCat[e.category]=(byCat[e.category]||0)+e.amount);const paid={},share={};t.partners.forEach(p=>{paid[p]=0;share[p]=0});t.expenses.forEach(e=>{paid[e.paidBy]=(paid[e.paidBy]||0)+e.amount;const each=e.amount/e.sharedBy.length;e.sharedBy.forEach(p=>share[p]=(share[p]||0)+each)});const net={};t.partners.forEach(p=>net[p]=(paid[p]||0)-(share[p]||0));const debtors=Object.entries(net).filter(([,v])=>v<-.01).map(([p,v])=>[p,-v]);const creditors=Object.entries(net).filter(([,v])=>v>.01).map(([p,v])=>[p,v]);const settles=[];let i=0,j=0;while(i<debtors.length&&j<creditors.length){const amt=Math.min(debtors[i][1],creditors[j][1]);settles.push(`${debtors[i][0]} pays ${creditors[j][0]} ${money(amt,t.currency)}`);debtors[i][1]-=amt;creditors[j][1]-=amt;if(debtors[i][1]<.01)i++;if(creditors[j][1]<.01)j++}
const d=document.getElementById('tripDetail');d.classList.remove('hidden');d.innerHTML=`<div class="sectionHead"><h2>${t.name}</h2><button class="primary small" onclick="addTripExpense('${t.id}')">+ Expense</button></div><div class="card"><div class="muted">Trip total</div><div class="balance" style="color:var(--text);font-size:28px">${money(total,t.currency)}</div><div class="tripTotals">${Object.entries(byCat).map(([k,v])=>`<div class="miniCard"><div class="muted">${k}</div><strong>${money(v,t.currency)}</strong></div>`).join('')}</div></div><div class="sectionHead"><h2>Settlement</h2></div><div class="stack">${settles.map(s=>`<div class="item"><div class="title">${s}</div></div>`).join('')||'<div class="item"><div class="sub">Everyone is settled.</div></div>'}</div><div class="sectionHead"><h2>Expenses</h2></div><div class="stack">${t.expenses.map(e=>`<div class="item"><div><div class="title">${e.description}</div><div class="sub">${e.category} · paid by ${e.paidBy}</div></div><div class="amount">${money(e.amount,t.currency)}</div></div>`).join('')||'<div class="item"><div class="sub">No trip expenses yet.</div></div>'}</div>`;d.scrollIntoView({behavior:'smooth'})}
window.addTripExpense=function(tripId){const t=state.trips.find(x=>x.id===tripId);document.getElementById('tripExpenseTripId').value=tripId;document.getElementById('tripExpensePaidBy').innerHTML=t.partners.map(p=>`<option>${p}</option>`).join('');document.getElementById('tripExpenseSharedBy').innerHTML=t.partners.map(p=>`<label><input type="checkbox" value="${p}" checked>${p}</label>`).join('');document.getElementById('tripExpenseDialog').showModal()}

function setScreen(id){document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===id));document.querySelectorAll('.tabbar button').forEach(b=>b.classList.toggle('active',b.dataset.screen===id));const names={overview:'Overview',accounts:'Accounts',add:'Add transaction',travel:'Travel',settings:'Settings'};document.getElementById('screenTitle').textContent=names[id]}
document.querySelectorAll('.tabbar button').forEach(b=>b.addEventListener('click',()=>setScreen(b.dataset.screen)));
document.querySelectorAll('#txTypeSeg button').forEach(b=>b.addEventListener('click',()=>{txType=b.dataset.type;document.querySelectorAll('#txTypeSeg button').forEach(x=>x.classList.toggle('active',x===b));document.getElementById('toAccountWrap').classList.toggle('hidden',txType!=='transfer');document.getElementById('txCategory').parentElement.classList.toggle('hidden',txType==='transfer')}));

document.getElementById('addAccountBtn').onclick=()=>document.getElementById('accountDialog').showModal();document.getElementById('accountForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const name=document.getElementById('accountName').value.trim();if(!name)return;state.accounts.push({id:id(),name,type:document.getElementById('accountType').value,currency:document.getElementById('accountCurrency').value,opening:Number(document.getElementById('accountOpening').value||0)});save();e.target.reset()});
document.getElementById('txDate').value=today();document.getElementById('txForm').addEventListener('submit',e=>{e.preventDefault();if(!state.accounts.length){alert('Add an account first.');return}const amount=Number(document.getElementById('txAmount').value);const accountId=document.getElementById('txAccount').value;const toAccountId=document.getElementById('txToAccount').value;if(txType==='transfer'&&accountId===toAccountId){alert('Choose two different accounts.');return}state.transactions.push({id:id(),type:txType,amount,accountId,toAccountId:txType==='transfer'?toAccountId:null,category:txType==='transfer'?'Transfer':document.getElementById('txCategory').value,date:document.getElementById('txDate').value,note:document.getElementById('txNote').value.trim()});save();e.target.reset();document.getElementById('txDate').value=today();setScreen('overview')});
document.getElementById('addTripBtn').onclick=()=>document.getElementById('tripDialog').showModal();document.getElementById('tripForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const name=document.getElementById('tripName').value.trim();if(!name)return;let partners=document.getElementById('tripPartners').value.split(',').map(x=>x.trim()).filter(Boolean);if(!partners.length)partners=['Me'];state.trips.push({id:id(),name,currency:document.getElementById('tripCurrency').value,partners,expenses:[]});save();e.target.reset()});
document.getElementById('tripExpenseForm').addEventListener('submit',e=>{if(e.submitter?.value==='cancel')return;const t=state.trips.find(x=>x.id===document.getElementById('tripExpenseTripId').value);const shared=[...document.querySelectorAll('#tripExpenseSharedBy input:checked')].map(x=>x.value);if(!shared.length){e.preventDefault();alert('Choose at least one person to share the expense.');return}t.expenses.push({id:id(),description:document.getElementById('tripExpenseDesc').value.trim(),amount:Number(document.getElementById('tripExpenseAmount').value),category:document.getElementById('tripExpenseCategory').value,paidBy:document.getElementById('tripExpensePaidBy').value,sharedBy:shared});save();setTimeout(()=>openTrip(t.id),0);e.target.reset()});
document.getElementById('homeCurrency').addEventListener('change',e=>{state.settings.homeCurrency=e.target.value;save()});
function exportData(){const blob=new Blob([JSON.stringify(state,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`PocketLedger-backup-${today()}.json`;a.click();URL.revokeObjectURL(a.href)}
document.getElementById('exportBtn').onclick=exportData;document.getElementById('backupBtn').onclick=exportData;document.getElementById('importInput').addEventListener('change',async e=>{const f=e.target.files[0];if(!f)return;try{state=JSON.parse(await f.text());save();alert('Backup restored.')}catch{alert('Invalid backup file.')}});document.getElementById('resetBtn').onclick=()=>{if(confirm('Erase all Pocket Ledger data stored on this device?')){state=defaults();save()}};
if('serviceWorker' in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));
renderAll();
